/**
 * bounds — clamping a contract, and resolving what an agent may touch.
 * ==================================================================
 * Two functions, both of which exist because the values they operate on
 * arrive from a workflow definition. A definition can be imported from a
 * file, generated by a model, or edited by hand — so nothing in it is
 * trusted, and in particular nothing in it may RAISE a limit.
 *
 * `resolveBounds` clamps. `resolveTools` narrows. Neither can widen.
 */

import { CAPABILITY_MANIFEST, describeFabricCapability } from '@aura/capability-fabric';
import type { AuthorityEnvelope } from '../envelope';
import { AGENT_CEILINGS, AGENT_DEFAULTS, type AgentBounds } from './types';

const clamp = (value: unknown, fallback: number, ceiling: number): number => {
  const n = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(n) || n <= 0) return fallback;
  return Math.min(Math.floor(n), ceiling);
};

/**
 * A node's configured bounds, clamped to the ceilings.
 *
 * Deliberately silent about a value that was too high rather than
 * rejecting the node: the clamped bound is safe, and refusing to run a
 * workflow because someone typed 1000 iterations would push people toward
 * removing the agent rather than bounding it. The EFFECTIVE bounds are
 * recorded on the trace, so what actually applied is never a mystery.
 */
export function resolveBounds(config: Record<string, unknown>): AgentBounds {
  return {
    maxIterations: clamp(config.maxIterations, AGENT_DEFAULTS.maxIterations, AGENT_CEILINGS.maxIterations),
    timeoutMs: clamp(config.timeoutMs, AGENT_DEFAULTS.timeoutMs, AGENT_CEILINGS.timeoutMs),
    maxTokens: clamp(config.maxTokens, AGENT_DEFAULTS.maxTokens, AGENT_CEILINGS.maxTokens),
    maxConsecutiveFailures: clamp(
      config.maxConsecutiveFailures,
      AGENT_DEFAULTS.maxConsecutiveFailures,
      AGENT_CEILINGS.maxConsecutiveFailures,
    ),
    tools: Array.isArray(config.tools) ? config.tools.filter((t): t is string => typeof t === 'string' && !!t) : [],
  };
}

/**
 * Why a tool is not available, as a code a UI can branch on.
 *
 * Codes rather than prose because the interface needs to treat these
 * differently — "your workflow does not ask for this" is a thing the
 * author can fix by editing the graph, and "this can never be given to an
 * agent" is not. Collapsing them into one sentence made the fixable case
 * look like the permanent one.
 *
 * None of them leaks anything sensitive: each names a rule that is already
 * documented, and none reports the state of a policy file or another
 * project.
 */
export type RefusalCode =
  /** No such capability exists in the manifest. */
  | 'unknown-capability'
  /** The Fabric knows it, but nothing registered can perform it. */
  | 'unsupported-capability'
  /** Excluded from ANY agent: the Fabric cannot undo it. */
  | 'agent-unsafe-irreversible'
  /** Excluded from ANY agent: only a person can satisfy its scope. */
  | 'agent-unsafe-human-only'
  /** Safe in principle, but this workflow's own authority does not include it. */
  | 'outside-envelope';

export interface ToolRefusal {
  capabilityId: string;
  code: RefusalCode;
  /** Plain language, safe to show. */
  reason: string;
  /** True when no edit to this workflow could ever make it available. */
  permanent: boolean;
}

export interface ResolvedTools {
  /** Capability ids the agent may actually request. */
  allowed: string[];
  /** Everything refused, classified. Surfaced, never swallowed. */
  refused: ToolRefusal[];
}

/**
 * "The agent's tools ≤ the workflow's permissions" — made structural.
 *
 * A requested capability survives only if all four hold:
 *
 *   1. the manifest defines it (no invented tool names);
 *   2. the workflow's envelope already contains it, so the human who
 *      approved the workflow's authority approved this too;
 *   3. it is not irreversible — an agent choosing on its own to do
 *      something the Fabric cannot undo is not a bounded agent, whatever
 *      its iteration count says;
 *   4. it needs no human-only scope. `account.authorize`, `resource.destroy`
 *      and `system.modify` are satisfiable only by a person, so offering
 *      them to a model is offering a tool that can only ever park.
 *
 * Rules 3 and 4 are stricter than the policy engine, which is allowed:
 * this narrows what is even offered. Nothing here loosens anything — every
 * surviving tool is still evaluated, gated and audited on every call.
 */
export function resolveTools(
  requested: string[],
  envelope: AuthorityEnvelope,
  /**
   * Which capabilities actually have an executor. Optional, because this
   * function must stay usable without a Fabric — but supplied in every
   * real call, because "add this and it becomes available" is false for a
   * declared extension point that nothing can perform yet, and telling an
   * author to fix something unfixable is worse than telling them nothing.
   */
  isSupported?: (capabilityId: string) => boolean,
): ResolvedTools {
  const inEnvelope = new Set(envelope.capabilities.map((c) => c.capabilityId));
  const allowed: string[] = [];
  const refused: ToolRefusal[] = [];

  for (const capabilityId of [...new Set(requested)].sort()) {
    const descriptor = describeFabricCapability(capabilityId);
    if (!descriptor) {
      refused.push({
        capabilityId,
        code: 'unknown-capability',
        reason: 'No such capability exists in AURA’s manifest.',
        permanent: true,
      });
      continue;
    }

    /* PERMANENT exclusions are checked FIRST.
     *
     * Both these and the envelope check exclude, so the order changes no
     * security property — but it changes the answer a person is given, and
     * the more specific answer is the useful one. Checking the envelope
     * first told an author that `git.push` was "not in this workflow's
     * authority", which reads as "add it and it will work". It never will:
     * an irreversible action is withheld from every agent in every
     * workflow, and saying so is the difference between a fixable message
     * and a misleading one.
     *
     * These exclusions are also what the envelope itself applies when it
     * admits an agent's tools, so the two can never disagree.
     */
    if (descriptor.irreversible) {
      refused.push({
        capabilityId,
        code: 'agent-unsafe-irreversible',
        reason: `${descriptor.name} cannot be undone by AURA, so it is never offered to an agent in any workflow. Put it in an explicit node a person can see before it runs.`,
        permanent: true,
      });
      continue;
    }
    const humanOnly = descriptor.permissions.find((p) => p === 'account.authorize' || p === 'resource.destroy' || p === 'system.modify');
    if (humanOnly) {
      refused.push({
        capabilityId,
        code: 'agent-unsafe-human-only',
        reason: `${descriptor.name} needs ${humanOnly}, which only a person can satisfy, so it is never offered to an agent in any workflow.`,
        permanent: true,
      });
      continue;
    }

    if (isSupported && !isSupported(capabilityId)) {
      refused.push({
        capabilityId,
        code: 'unsupported-capability',
        reason: `${descriptor.name} is declared but nothing on this machine can perform it yet, so it cannot be given to an agent.`,
        permanent: false,
      });
      continue;
    }

    // Fixable: the author can widen the workflow, within the same rules.
    if (!inEnvelope.has(capabilityId)) {
      refused.push({
        capabilityId,
        code: 'outside-envelope',
        reason: `This workflow's authority does not include ${descriptor.name.toLowerCase()}. Add it to this agent's tools, or to a node in the workflow, and it becomes available.`,
        permanent: false,
      });
      continue;
    }
    allowed.push(capabilityId);
  }

  return { allowed, refused };
}

/**
 * The tool descriptions an agent is shown.
 *
 * Built from the manifest, never from the workflow definition and never
 * from the prompt. This is the "tool poisoning" control: a hostile
 * definition cannot describe a capability as something it is not, because
 * the description the model reads does not come from the definition at all.
 */
/**
 * Everything the manifest holds, classified for THIS workflow.
 *
 * The tool picker needs more than the allowed set: it has to render what
 * cannot be chosen and say why, and the difference between "add this to
 * your workflow" and "no agent may ever have this" is the difference
 * between a fixable message and a misleading one.
 */
export function classifyAllTools(
  envelope: AuthorityEnvelope,
  isSupported?: (capabilityId: string) => boolean,
): { allowed: string[]; refused: ToolRefusal[] } {
  return resolveTools(CAPABILITY_MANIFEST.map((c) => c.id), envelope, isSupported);
}

export function describeTools(allowed: string[]): { name: string; description: string; input: { name: string; type: string; required: boolean; description: string }[] }[] {
  const out = [];
  for (const id of allowed) {
    const d = describeFabricCapability(id);
    if (!d) continue;
    out.push({
      name: d.id,
      description: `${d.name}. ${d.description}`,
      input: d.input.map((f) => ({ name: f.name, type: f.type, required: f.required, description: f.description })),
    });
  }
  return out;
}
