"""P1-E: generated-artifact hygiene regression tests.

Bytecode and caches are regenerable and must never be tracked;
graphify-out/ live deliverables stay tracked BY CONVENTION (see the
graphify section of .gitignore) and must not be "cleaned" away.
Both directions are pinned here. Skipped outside a git checkout.
"""

import shutil
import subprocess

import pytest

GIT = shutil.which("git")


def _git_ls_files(repo_root: str) -> list[str] | None:
    if GIT is None:
        return None
    try:
        out = subprocess.run(
            [GIT, "-C", repo_root, "ls-files"],
            capture_output=True, text=True, timeout=60, check=True)
    except (subprocess.SubprocessError, OSError):
        return None
    return out.stdout.splitlines()


def _repo_root() -> str:
    from pathlib import Path

    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / ".git").exists():
            return str(parent)
    return ""


def test_no_tracked_bytecode_or_caches() -> None:
    root = _repo_root()
    if not root or _git_ls_files(root) is None:
        pytest.skip("not a git checkout")
        return
    tracked = _git_ls_files(root) or []
    offenders = [p for p in tracked
                 if "__pycache__" in p or p.endswith((".pyc", ".pyo"))]
    assert offenders == [], f"generated bytecode tracked: {offenders}"


def test_caches_ignored() -> None:
    root = _repo_root()
    if not root or GIT is None:
        pytest.skip("not a git checkout")
        return
    try:
        out = subprocess.run(
            [GIT, "-C", root, "check-ignore", ".pytest_cache",
             ".ruff_cache", "backend/tests/__pycache__"],
            capture_output=True, text=True, timeout=60)
    except (subprocess.SubprocessError, OSError):
        pytest.skip("git check-ignore unavailable")
        return
    assert out.returncode == 0, "caches must be git-ignored"


def test_graphify_live_deliverable_stays_tracked() -> None:
    root = _repo_root()
    if not root or _git_ls_files(root) is None:
        pytest.skip("not a git checkout")
        return
    tracked = _git_ls_files(root) or []
    for pinned in ("graphify-out/graph.json",
                   "graphify-out/GRAPH_REPORT.md"):
        assert pinned in tracked, f"{pinned} must stay tracked"
