"""Model provisioning for offline Docling operation.

Strategy: warm the real pipeline once (a tiny PDF + a tiny image), which
pulls every artifact the configured engines need — layout weights,
table structure, OCR models — into the dedicated AURA cache. Then write
``MANIFEST.json`` recording the exact source and license of each cached
model, so offline/air-gapped installs are reproducible and auditable.

No document content is involved: fixtures are generated bytes, and the
manifest records models only.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Optional

MANIFEST_NAME = "MANIFEST.json"


def default_cache_dir() -> Path:
    from .docling_engine import model_cache_dir

    return model_cache_dir()


def collect_model_records(cache: Path) -> list[dict[str, Any]]:
    """Inventory cached model files with hashes (informational)."""
    records: list[dict[str, Any]] = []
    if not cache.is_dir():
        return records
    for path in sorted(cache.rglob("*")):
        if not path.is_file() or path.name == MANIFEST_NAME:
            continue
        try:
            digest = hashlib.sha256(path.read_bytes()).hexdigest()
            size = path.stat().st_size
        except OSError:
            continue
        records.append({
            "path": str(path.relative_to(cache)),
            "sha256": digest,
            "sizeBytes": size,
        })
    return records


def write_manifest(cache: Path, docling_version: str,
                   ocr_engines: list[str], extra: Optional[dict] = None) -> Path:
    """Write MANIFEST.json: the offline-readiness contract."""
    manifest = {
        "provisionedAt": datetime.datetime.now(
            datetime.timezone.utc).isoformat(),
        "doclingVersion": docling_version,
        "ocrEngines": ocr_engines,
        "knownSources": [
            {"name": "docling-project/docling-layout-heron",
             "source": "https://huggingface.co/docling-project/"
                       "docling-layout-heron",
             "license": "Apache-2.0 (verified from repo model card)"},
            {"name": "docling-project/docling-models "
                     "(table structure + pipeline artifacts)",
             "source": "https://huggingface.co/docling-project/"
                       "docling-models",
             "license": "see repo model cards before redistribution "
                        "(not individually verified)"},
            {"name": "docling Python package",
             "source": "https://github.com/docling-project/docling",
             "license": "MIT"},
            {"name": "RapidOCR ONNX models",
             "source": "https://github.com/RapidAI/RapidOCR "
                        "(auto-downloaded on first use)",
             "license": "Apache-2.0"},
            {"name": "Tesseract traineddata (system package, if used)",
             "source": "https://github.com/tesseract-ocr/tessdata",
             "license": "Apache-2.0"},
        ],
        "files": collect_model_records(cache),
        "extra": extra or {},
    }
    cache.mkdir(parents=True, exist_ok=True)
    target = cache / MANIFEST_NAME
    tmp = target.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    tmp.replace(target)
    return target


def provision(cache: Optional[Path] = None,
              ocr_engine: str = "auto",
              include_samples: bool = True) -> dict[str, Any]:
    """Download + cache all required models. Returns a JSONable report.

    Steps: resolve cache dir → build one converter per needed path (which
    triggers HF downloads) → convert tiny in-memory fixtures → write
    manifest. Raises on download failure (provisioning must be loud).
    """
    from .docling_engine import (  # local import: docling optional
        DoclingEngine,
        docling_version,
        model_cache_dir,
    )
    from .doctypes import IsolationMode, OcrEngine
    from .document_engine import EngineConfig

    target = cache or model_cache_dir()
    target.mkdir(parents=True, exist_ok=True)

    try:
        want_ocr = OcrEngine(ocr_engine.lower())
    except ValueError:
        want_ocr = OcrEngine.AUTO

    config = EngineConfig(ocr_engine=want_ocr,
                          isolation=IsolationMode.IN_PROCESS,
                          timeout_s=600.0)
    engine = DoclingEngine(model_cache=str(target))
    if not engine.is_installed():
        raise RuntimeError("docling package not installed; cannot provision")

    warmed: list[str] = []
    if include_samples:
        from .secure import managed_temp_dir

        _PDF = (_sample_pdf_bytes(), ".pdf")
        _PNG = (_sample_png_bytes(), ".png")
        with managed_temp_dir(prefix="aura-provision-") as tmpdir:
            for payload, suffix in (_PDF, _PNG):
                sample = tmpdir / f"warmup{suffix}"
                sample.write_bytes(payload)
                from .doctypes import DocumentConversionRequest

                result = engine.convert(DocumentConversionRequest(
                    path=str(sample)))
                warmed.append(f"{suffix}: {result.document_status.value} "
                              f"(engine={result.engine} "
                              f"ocr={result.ocr_used or 'none'})")

    manifest_path = write_manifest(
        target, docling_version(), engine.capabilities().ocr_engines,
        extra={"warmed": warmed})
    return {
        "cacheDir": str(target),
        "doclingVersion": docling_version(),
        "ocrEngines": engine.capabilities().ocr_engines,
        "warmed": warmed,
        "manifest": str(manifest_path),
    }


def _sample_pdf_bytes() -> bytes:
    """Minimal one-page PDF with a text layer (no library needed)."""
    body = (b"BT /F1 18 Tf 72 720 Td (Provisioning warmup document.) Tj ET")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length %d >>\nstream\n" % len(body) + body + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % i + obj + b"\nendobj\n"
    xref = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += b"%010d 00000 n \n" % off
    out += (b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n"
            % (len(objects) + 1, xref))
    return bytes(out)


def _sample_png_bytes() -> bytes:
    """1x1 white PNG (valid image, no text) for pipeline warmup."""
    import base64

    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8"
        "/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==")


def main(argv: Optional[list[str]] = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Provision AURA Docling model cache for offline use.")
    parser.add_argument("--cache", default="",
                        help="model cache dir (default: $AURA_DOCS_MODEL_CACHE"
                             " or $AURA_HOME/models/docling)")
    parser.add_argument("--ocr", default="auto",
                        help="ocr engine to warm (auto|rapidocr|tesseract|none)")
    parser.add_argument("--no-samples", action="store_true",
                        help="record manifest without warming conversions")
    args = parser.parse_args(argv)
    try:
        report = provision(
            cache=Path(args.cache).expanduser() if args.cache else None,
            ocr_engine=args.ocr,
            include_samples=not args.no_samples)
    except Exception as exc:
        print(f"provisioning failed: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
