import { useRef, useCallback } from 'react';
import * as THREE from 'three';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';

export interface LayerDef {
  title: string;
  subtitle?: string;
  items?: string[];
  color: string;
  width?: number;
}

const DEFAULT_LAYERS: LayerDef[] = [
  { title: 'AURA HUB', subtitle: 'AI Operating Environment for Software Engineering', color: '#6366f1', width: 14 },
  { title: 'User Interface', items: ['Chat Interface', 'Project Explorer', 'Intelligence Dashboard', 'Settings (BYOAK Providers)'], color: '#3b82f6' },
  { title: 'Conversation Layer', items: ['Conversation Manager', 'History Management', 'Project Isolation', 'Persistence'], color: '#06b6d4' },
  { title: 'Repository Intelligence', items: ['Identity · Intent · Summaries · Memory', 'Glossary · Health · Verification', 'Architecture · Validation · Change', 'Personality · Versioning · Performance', 'Workspace · Cross-Repo · Agent APIs'], color: '#8b5cf6', width: 15 },
  { title: 'Context Assembly', items: ['Document Priority', 'Context Builder', 'Confidence Engine', 'Prompt Assembly', 'Repository Facts'], color: '#a855f7' },
  { title: 'Provider Abstraction', items: ['generate() · stream() · cancel()', 'health() · listModels()'], color: '#ec4899' },
  { title: 'Model Providers (BYOAK)', items: ['NVIDIA · OpenAI · Anthropic · Gemini', 'Groq · Mistral · OpenRouter · Kimi'], color: '#f43f5e', width: 14 },
  { title: 'Streaming Response Layer', items: ['Token Streaming', 'Response Assembly', 'Usage Statistics', 'Conversation Persistence'], color: '#f97316' },
  { title: 'Final Response', subtitle: 'Repository-Aware AI Answer Generated by AURA Hub', color: '#22c55e', width: 12 },
];

const BOX_H = 1.0;
const BOX_D = 1.8;
const GAP = 0.9;

function makeLayerTex(layer: LayerDef, bw: number): THREE.CanvasTexture {
  const s = 2;
  const cw = Math.round(bw * 60 * s);
  const ch = Math.round(BOX_H * 60 * s);
  const canvas = document.createElement('canvas');
  canvas.width = cw;
  canvas.height = ch;
  const ctx = canvas.getContext('2d')!;
  ctx.fillStyle = 'rgba(10,14,23,0.92)';
  ctx.beginPath();
  ctx.roundRect(0, 0, cw, ch, 12 * s);
  ctx.fill();
  ctx.strokeStyle = layer.color;
  ctx.lineWidth = 2.5 * s;
  ctx.shadowColor = layer.color;
  ctx.shadowBlur = 12 * s;
  ctx.beginPath();
  ctx.roundRect(2 * s, 2 * s, cw - 4 * s, ch - 4 * s, 12 * s);
  ctx.stroke();
  ctx.shadowBlur = 0;
  ctx.fillStyle = layer.color;
  ctx.font = `bold ${(layer.subtitle && !layer.items ? 20 : 16) * s}px system-ui, sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  if (layer.items && layer.items.length > 0) {
    ctx.fillText(layer.title, cw / 2, ch * 0.22);
    ctx.fillStyle = '#cbd5e1';
    ctx.font = `${10 * s}px system-ui, sans-serif`;
    layer.items.forEach((item, i) => { ctx.fillText(item, cw / 2, ch * 0.55 + i * 11 * s); });
  } else {
    ctx.fillText(layer.title, cw / 2, ch * 0.38);
    if (layer.subtitle) {
      ctx.fillStyle = '#94a3b8';
      ctx.font = `${9 * s}px system-ui, sans-serif`;
      ctx.fillText(layer.subtitle, cw / 2, ch * 0.62);
    }
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.needsUpdate = true;
  return tex;
}

function makeArrowTex(color: string): THREE.CanvasTexture {
  const canvas = document.createElement('canvas');
  canvas.width = 64;
  canvas.height = 128;
  const ctx = canvas.getContext('2d')!;
  ctx.clearRect(0, 0, 64, 128);
  ctx.strokeStyle = color;
  ctx.lineWidth = 3;
  ctx.shadowColor = color;
  ctx.shadowBlur = 8;
  ctx.beginPath();
  ctx.moveTo(32, 0);
  ctx.lineTo(32, 90);
  ctx.stroke();
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.moveTo(32, 128);
  ctx.lineTo(18, 90);
  ctx.lineTo(46, 90);
  ctx.closePath();
  ctx.fill();
  const tex = new THREE.CanvasTexture(canvas);
  tex.needsUpdate = true;
  return tex;
}

export function ArchitectureDiagram3D({ layers: dynamicLayers, onRenderFailure }: { layers?: LayerDef[]; onRenderFailure?: () => void } = {}) {
  const cleanupRef = useRef<(() => void) | null>(null);
  const layersRef = useRef<LayerDef[]>(dynamicLayers ?? DEFAULT_LAYERS);
  const failureRef = useRef(onRenderFailure);
  failureRef.current = onRenderFailure;

  // Update layers when prop changes
  if (dynamicLayers && dynamicLayers.length) layersRef.current = dynamicLayers;

  const containerRef = useCallback((container: HTMLDivElement | null) => {
    if (cleanupRef.current) { cleanupRef.current(); cleanupRef.current = null; }
    if (!container) return;

    const w = container.clientWidth || 800;
    const h = container.clientHeight || 600;

    // Scene
    const scene = new THREE.Scene();
    scene.background = new THREE.Color('#0a0e17');

    const camera = new THREE.PerspectiveCamera(50, w / h, 0.1, 200);
    camera.position.set(0, -2, 34);

    // WebGL context creation can fail (or silently degrade) in some embedded
    // webviews — never leave a blank pane, fall back to the 2D graph view.
    let renderer: any;
    try {
      renderer = new THREE.WebGLRenderer({ antialias: true });
    } catch {
      failureRef.current?.();
      return;
    }
    const gl = renderer.getContext();
    if (!gl) {
      renderer.dispose();
      failureRef.current?.();
      return;
    }
    renderer.setSize(w, h);
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    container.appendChild(renderer.domElement);

    // Lights
    scene.add(new THREE.AmbientLight(0xffffff, 0.6));
    const dl = new THREE.DirectionalLight(0xffffff, 0.8);
    dl.position.set(5, 10, 7);
    scene.add(dl);

    // Build layers
    const L = layersRef.current;
    const totalH = L.length * (BOX_H + GAP);
    const startY = totalH / 2;
    const group = new THREE.Group();
    const boxMeshes: THREE.Mesh[] = [];

    L.forEach((layer, i) => {
      const bw = layer.width ?? 12;
      const y = startY - i * (BOX_H + GAP);

      const face = new THREE.Mesh(
        new THREE.PlaneGeometry(bw, BOX_H),
        new THREE.MeshBasicMaterial({ map: makeLayerTex(layer, bw), transparent: true }),
      );
      face.position.set(0, y, BOX_D / 2);
      face.userData = { layerIndex: i };
      group.add(face);
      boxMeshes.push(face);

      const wire = new THREE.LineSegments(
        new THREE.EdgesGeometry(new THREE.BoxGeometry(bw, BOX_H, BOX_D)),
        new THREE.LineBasicMaterial({ color: layer.color, transparent: true, opacity: 0.35 }),
      );
      wire.position.set(0, y, 0);
      wire.userData = { layerIndex: i };
      group.add(wire);

      const glow = new THREE.Mesh(
        new THREE.PlaneGeometry(bw + 1, BOX_H + 0.6),
        new THREE.MeshBasicMaterial({ color: layer.color, transparent: true, opacity: 0.04, side: THREE.DoubleSide }),
      );
      glow.position.set(0, y, -0.2);
      group.add(glow);

      if (i < L.length - 1) {
        const arrow = new THREE.Mesh(
          new THREE.PlaneGeometry(0.5, GAP * 0.7),
          new THREE.MeshBasicMaterial({ map: makeArrowTex(L[i + 1].color), transparent: true, opacity: 0.7, side: THREE.DoubleSide }),
        );
        arrow.position.set(0, y - BOX_H / 2 - GAP / 2, BOX_D / 2 + 0.01);
        group.add(arrow);
      }
    });

    group.position.y = -startY + BOX_H / 2;
    scene.add(group);

    // Bloom
    const composer = new EffectComposer(renderer);
    composer.addPass(new RenderPass(scene, camera));
    composer.addPass(new UnrealBloomPass(new THREE.Vector2(w, h), 0.4, 0.3, 0.9));

    // Raycaster for hit detection
    const raycaster = new THREE.Raycaster();
    const pointer = new THREE.Vector2();

    // Interaction state
    type Mode = 'idle' | 'orbit' | 'drag';
    let mode: Mode = 'idle';
    let lastX = 0;
    let lastY = 0;
    let lastTap = 0;
    let dragTarget: THREE.Object3D | null = null;
    let dragPlane = new THREE.Plane();
    let dragOffset = new THREE.Vector3();

    function getPointer(e: PointerEvent) {
      const rect = renderer.domElement.getBoundingClientRect();
      return { x: e.clientX - rect.left, y: e.clientY - rect.top };
    }

    function hitTest(px: number, py: number): THREE.Object3D | null {
      const rect = renderer.domElement.getBoundingClientRect();
      pointer.x = ((px - rect.left) / rect.width) * 2 - 1;
      pointer.y = -((py - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(pointer, camera);
      const hits = raycaster.intersectObjects(boxMeshes, false);
      return hits.length > 0 ? hits[0].object : null;
    }

    function getWorldPoint(px: number, py: number, target: THREE.Vector3) {
      const rect = renderer.domElement.getBoundingClientRect();
      pointer.x = ((px - rect.left) / rect.width) * 2 - 1;
      pointer.y = -((py - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(pointer, camera);
      raycaster.ray.intersectPlane(dragPlane, target);
    }

    // Smooth camera orbit (no OrbitControls — pure manual)
    const camTarget = new THREE.Vector3(0, -1.5, 0);
    let camTheta = 0;
    let camPhi = 0;
    let camDist = 32;

    function updateCamera() {
      camera.position.x = camTarget.x + camDist * Math.sin(camTheta) * Math.cos(camPhi);
      camera.position.y = camTarget.y + camDist * Math.sin(camPhi);
      camera.position.z = camTarget.z + camDist * Math.cos(camTheta) * Math.cos(camPhi);
      camera.lookAt(camTarget);
    }
    updateCamera();

    // Double-tap detection
    const DOUBLE_TAP_MS = 300;

    function onPointerDown(e: PointerEvent) {
      const now = Date.now();
      const isDoubleTap = (now - lastTap) < DOUBLE_TAP_MS;
      lastTap = now;

      const p = getPointer(e);
      lastX = p.x;
      lastY = p.y;

      if (isDoubleTap) {
        const hit = hitTest(e.clientX, e.clientY);
        if (hit) {
          // Double-tap on structure → drag mode
          mode = 'drag';
          dragTarget = hit;
          dragTarget.getWorldPosition(dragOffset);
          // Set drag plane perpendicular to camera
          const camDir = new THREE.Vector3();
          camera.getWorldDirection(camDir);
          dragPlane.setFromNormalAndCoplanarPoint(camDir.clone().negate(), dragOffset);
          renderer.domElement.style.cursor = 'move';
        } else {
          // Double-tap on empty → orbit mode
          mode = 'orbit';
          renderer.domElement.style.cursor = 'grabbing';
        }
      } else {
        // Single tap — prepare for potential orbit on drag
        mode = 'idle';
      }

      renderer.domElement.setPointerCapture(e.pointerId);
    }

    function onPointerMove(e: PointerEvent) {
      if (mode === 'idle') return;

      const p = getPointer(e);
      const dx = p.x - lastX;
      const dy = p.y - lastY;
      lastX = p.x;
      lastY = p.y;

      if (mode === 'orbit') {
        camTheta -= dx * 0.005;
        camPhi += dy * 0.005;
        camPhi = Math.max(-Math.PI / 2.2, Math.min(Math.PI / 2.2, camPhi));
        updateCamera();
      } else if (mode === 'drag' && dragTarget) {
        const worldPt = new THREE.Vector3();
        getWorldPoint(e.clientX, e.clientY, worldPt);
        if (worldPt) {
          dragTarget.position.x = worldPt.x - dragOffset.x;
        }
      }
    }

    function onPointerUp(e: PointerEvent) {
      if (mode === 'drag' && dragTarget) {
        // Snap back after a short delay
        const target = dragTarget;
        const snapBack = () => {
          target.position.x *= 0.85;
          if (Math.abs(target.position.x) > 0.01) {
            requestAnimationFrame(snapBack);
          } else {
            target.position.x = 0;
          }
        };
        requestAnimationFrame(snapBack);
        dragTarget = null;
      }
      mode = 'idle';
      renderer.domElement.style.cursor = 'grab';
      renderer.domElement.releasePointerCapture(e.pointerId);
    }

    function onWheel(e: WheelEvent) {
      e.preventDefault();
      camDist += e.deltaY * 0.02;
      camDist = Math.max(8, Math.min(80, camDist));
      updateCamera();
    }

    renderer.domElement.addEventListener('pointerdown', onPointerDown);
    renderer.domElement.addEventListener('pointermove', onPointerMove);
    renderer.domElement.addEventListener('pointerup', onPointerUp);
    renderer.domElement.addEventListener('wheel', onWheel, { passive: false });

    // Animation loop
    let raf = 0;
    const animate = () => {
      composer.render();
      raf = requestAnimationFrame(animate);
    };
    animate();

    // Resize
    const ro = new ResizeObserver(() => {
      const nw = container.clientWidth;
      const nh = container.clientHeight;
      if (nw > 0 && nh > 0) {
        camera.aspect = nw / nh;
        camera.updateProjectionMatrix();
        renderer.setSize(nw, nh);
        composer.setSize(nw, nh);
      }
    });
    ro.observe(container);

    cleanupRef.current = () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      renderer.domElement.removeEventListener('pointerdown', onPointerDown);
      renderer.domElement.removeEventListener('pointermove', onPointerMove);
      renderer.domElement.removeEventListener('pointerup', onPointerUp);
      renderer.domElement.removeEventListener('wheel', onWheel);
      renderer.dispose();
      composer.dispose();
      if (container.contains(renderer.domElement)) container.removeChild(renderer.domElement);
    };
  }, []);

  return (
    <div
      ref={containerRef}
      style={{ width: '100%', height: '100%', minHeight: 650, paddingBottom: 40, background: '#0a0e17', touchAction: 'none', cursor: 'grab' }}
    />
  );
}
