"""Frozen canonicalization vectors — V1, V2, V3a, V3b, V4, G1 must be byte-exact.

Ground truth: docs/migration/canonicalization-vectors.json (generated by the
REAL TypeScript implementations at revision 141d101). A failure here is a
migration blocker: nothing above P1 may proceed.
"""

from __future__ import annotations

import json

import pytest

from aura.canonical import fingerprint_invocation, graph_hash

from _paths import VECTORS_FILE


@pytest.fixture(scope="module")
def vectors() -> dict:
    return json.loads(VECTORS_FILE.read_text(encoding="utf-8"))


def test_all_fingerprint_vectors(vectors):
    for v in vectors["fingerprintInvocation"]["vectors"]:
        a = v["args"]
        got = fingerprint_invocation(a["capabilityId"], a["input"], a["context"])
        assert got == v["digest"], f"{v['name']}: got {got}, want {v['digest']}"


def test_v2_equals_v1_key_order_independence(vectors):
    digests = [v["digest"] for v in vectors["fingerprintInvocation"]["vectors"]]
    assert digests[0] == digests[1], "top-level key order MUST NOT change the digest"


def test_v3_nested_order_is_significant(vectors):
    digests = [v["digest"] for v in vectors["fingerprintInvocation"]["vectors"]]
    assert digests[2] != digests[3], (
        "nested objects are NOT canonicalized — insertion order is significant"
    )


def test_g1_graph_hash(vectors):
    g = vectors["graphHash"]["vectors"][0]
    nodes = [{"id": n["id"], "type": n["type"], "x": 0, "y": 0, "config": n["config"]} for n in g["nodes"]]
    got = graph_hash(nodes, g["edges"])
    assert got == g["digest"], f"G1: got {got}, want {g['digest']}"


def test_graph_hash_ignores_layout_and_edge_ids(vectors):
    """x/y jitter and edge-id noise MUST NOT change the digest (versions.ts contract)."""
    g = vectors["graphHash"]["vectors"][0]
    mk_nodes = lambda jitter: [
        {"id": n["id"], "type": n["type"], "x": 10.0 + jitter, "y": -jitter, "config": dict(n["config"])}
        for n in g["nodes"]
    ]
    edges_plain = [{"from": e["from"], "fromPort": e["fromPort"], "to": e["to"]} for e in g["edges"]]
    edges_noisy = [dict(id=f"noise-{i}", **e) for i, e in enumerate(edges_plain)]
    assert graph_hash(mk_nodes(0.0), edges_plain) == g["digest"]
    assert graph_hash(mk_nodes(42.0), edges_noisy) == g["digest"]
