#!/usr/bin/env python3
"""Provision the AURA Docling model cache for local/offline conversion.

One-time download of required model weights into the dedicated AURA
cache, with an auditable MANIFEST.json (source + license per model).

Usage:
    python scripts/provision-docling-models.py [--cache DIR] [--ocr ENGINE]

Requires: pip install "aura-backend[docling]" (CPU torch first; see
backend/pyproject.toml). Never sends document content anywhere: warmup
fixtures are generated bytes.
"""

from __future__ import annotations

import os
import sys

BACKEND_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "backend")
sys.path.insert(0, os.path.abspath(BACKEND_DIR))

from aura.multimodal.provision import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main())
